//
// Created by hhvvg on 8/18/24.
//

#ifndef TOKEN_TYPE_HPP
#define TOKEN_TYPE_HPP

enum TokenType {
    L_PAREN, R_PAREN, L_BRACE, R_BRACE, L_BRACKET, R_BRACKET,
    COMMA, COMMENT, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

    BACKSLASH, BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    IDENTIFIER, STRING, INT, DOUBLE,

    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NULL_PTR, OR,
    PRINT, RETURN, SUPER, THIS, TRUE, VAR, VARARGS, VERTICAL_BAR, WHILE,

    QUESTION_MARK, COLON,

    FILE_EOF
};

#endif //TOKEN_TYPE_HPP
